import {BARN_ROUNDS,BARN_ITEMS,BARN_STORAGE,emptyBarnSave,sanitizeBarnSave,BarnBoard,guideFirst,guideSecond} from './barnyard-rules.js';
import {barnItem,barnScene} from './barnyard-art.js';
import {icon,pip} from './art.js';

const $=id=>document.getElementById(id),delay=ms=>new Promise(r=>setTimeout(r,ms));
export function setupBarnyard({show,goHome}){
 let save=emptyBarnSave(),board=null,roundId=1,generation=0,audio;
 try{save=sanitizeBarnSave(JSON.parse(localStorage.getItem(BARN_STORAGE)));}catch{}
 const persist=()=>{try{localStorage.setItem(BARN_STORAGE,JSON.stringify(save));}catch{}}
 document.querySelectorAll('.barn-world').forEach(el=>el.innerHTML=barnScene());
 $('barnyard-icon').innerHTML=barnItem('cow');$('barn-pip').innerHTML=pip();$('barn-explore-pip').innerHTML=pip();
 $('barn-home').innerHTML=icon('home');$('barn-explore-home').innerHTML=icon('home');$('barn-pointer').innerHTML=icon('hand');
 $('barn-next').innerHTML=icon('next');
 function setSoundButtons(){ $('barn-voice').innerHTML=icon(save.voice?'sound':'mute');$('barn-effects').innerHTML=icon(save.effects?'sun':'moon');$('barn-voice').setAttribute('aria-pressed',String(save.voice));$('barn-effects').setAttribute('aria-pressed',String(save.effects));$('barn-voice').setAttribute('aria-label',save.voice?'Mute voice':'Enable voice');$('barn-effects').setAttribute('aria-label',save.effects?'Mute music and effects':'Enable music and effects'); }
 function speak(text,explore=false){(explore?$('barn-explore-caption'):$('barn-caption')).textContent=text;if(!save.voice)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.9;u.pitch=1.08;speechSynthesis.speak(u);}catch{}}
 function tone(kind='tap'){if(!save.effects)return;try{audio??=new AudioContext();audio.resume();const notes=kind==='match'?[659,880]:kind==='splash'?[260,390]:kind==='moo'?[170,125]:kind==='baa'?[260,310]:[440];notes.forEach((n,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.09;o.frequency.value=n;o.type=['moo','baa'].includes(kind)?'triangle':'sine';g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.06,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.23);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.25);});}catch{}}
 function available(){return board.available();}
 function start(id){generation++;roundId=id;board=new BarnBoard(id);const r=BARN_ROUNDS[id-1];$('barn-round').textContent='ROUND '+id;$('barn-title').textContent=r.name;$('barn-round-actions').hidden=true;renderDiscoveries($('barn-discoveries'),false);show('barn-match');draw();turn();speak(id===1?'You go first. Flip any two cards!':'More friends are hiding. You go first again!');setTimeout(()=>$('barn-cards').querySelector('button:not(:disabled)')?.focus({preventScroll:true}),0);}
 function draw(){$('barn-cards').dataset.pairs=4;$('barn-cards').innerHTML=board.deck.map((c,i)=>`<button class="memory-card" data-barn-card="${i}" aria-label="Card ${i+1}, face down"><span class="card-inner"><span class="card-face card-back">${icon('leaf')}<i></i></span><span class="card-face card-front" style="--paper:#f6cf8a">${barnItem(c.pair)}</span></span><span class="match-tick">${icon('check')}</span></button>`).join('');update();}
 function update(){if(!board)return;const locked=board.turn!=='child'||board.phase!=='ready';$('barn-cards').querySelectorAll('[data-barn-card]').forEach((el,i)=>{const c=board.deck[i],open=board.open.includes(i),matched=board.matched.has(c.pair);el.classList.toggle('flipped',open);el.classList.toggle('matched',matched);el.disabled=locked||open||matched;el.setAttribute('aria-label',`Card ${i+1}, ${open||matched?BARN_ITEMS[c.pair].name:'face down'}${matched?', matched':''}`);});$('barn-hint').disabled=locked;$('barn-progress').innerHTML=`${save.discoveries.length} of 8<br><small>FOUND</small>`;}
 function turn(){if(!board)return;const guide=board.turn==='guide';$('barn-turn').textContent=guide?"Pip's turn":'Your turn';$('barn-turn').classList.toggle('guide',guide);update();}
 async function childFlip(i){if(!board||board.turn!=='child'||board.phase!=='ready')return;const card=board.reveal(i);if(!card)return;tone();update();if(board.open.length===1)speak(`A ${BARN_ITEMS[card.pair].name.toLowerCase()}! Choose one more.`,false);if(board.phase==='resolving')await resolve();}
 async function resolve(){const token=generation,actor=board.turn;await delay(actor==='guide'?750:1050);if(token!==generation||!board)return;const result=board.resolve();if(result.match){tone('match');await discover(result.pair,token);if(token!==generation||!board)return;speak(`We found the ${BARN_ITEMS[result.pair].name.toLowerCase()}! It joined our barnyard.`);}else{speak(actor==='child'?'Those were different. My turn to look!':'Not a pair this time. Your turn!');await delay(600);}if(token!==generation||!board)return;update();if(result.complete){if(!save.completed.includes(roundId))save.completed.push(roundId);persist();await delay(650);if(token===generation)finishRound();}else if(board.turn==='guide'){turn();guideTurn(token);}else{turn();}}
 async function discover(pair,token){const fresh=!save.discoveries.includes(pair);if(fresh)save.discoveries.push(pair);persist();const source=[...$('barn-cards').children].find(el=>board.deck[Number(el.dataset.barnCard)].pair===pair),rect=source?.getBoundingClientRect();renderDiscoveries($('barn-discoveries'),false,pair);update();const target=$('barn-discoveries').querySelector(`[data-barn-object="${pair}"]`);if(rect&&target&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const end=target.getBoundingClientRect(),fly=document.createElement('span');fly.className='memory-card barn-fly flipped';fly.style.cssText=`left:${rect.left}px;top:${rect.top}px;width:${rect.width}px;height:${rect.height}px`;fly.innerHTML=`<span class="card-face card-front" style="--paper:#f6cf8a">${barnItem(pair)}</span>`;document.body.append(fly);requestAnimationFrame(()=>{fly.style.left=end.left+'px';fly.style.top=end.top+'px';fly.style.scale='.5';fly.style.opacity='0';});setTimeout(()=>fly.remove(),650);}await delay(560);return token===generation;}
 async function guideTurn(token){speak('Let me remember what we have seen.');await delay(650);if(token!==generation||!board)return;const first=guideFirst(board.memory,available());await pointFlip(first,token);if(token!==generation||!board)return;await delay(450);const second=guideSecond(board.memory,available(),first,board.deck[first].pair);await pointFlip(second,token);if(token===generation&&board)resolve();}
 async function pointFlip(i,token){const el=$('barn-cards').querySelector(`[data-barn-card="${i}"]`),r=el.getBoundingClientRect(),p=$('barn-pointer');p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.classList.add('show');el.classList.add('barn-guide-target');await delay(520);if(token!==generation||!board)return;board.reveal(i);tone();update();el.classList.remove('barn-guide-target');await delay(430);p.classList.remove('show');}
 function hint(){if(!board||board.turn!=='child'||board.phase!=='ready')return;const h=board.memory.hint(available()),place=i=>(i<4?'top':'bottom')+' row';if(h.type==='pair')speak(`I remember two ${BARN_ITEMS[h.pair].name.toLowerCase()} cards, both around the ${place(h.indices[0])}.`);else if(h.type==='single')speak(`I think we saw the ${BARN_ITEMS[h.pair].name.toLowerCase()} near the ${place(h.index)}.`);else speak("I don't remember one yet. Let's explore any card!");}
 function finishRound(){generation++;board=null;showExplore(true);$('barn-round-actions').hidden=false;$('barn-complete-title').textContent=roundId===2?'Our barnyard is complete!':'Look what we found!';$('barn-next').setAttribute('aria-label',roundId===1?'Next round':'Explore everything');speak(roundId===1?'What a team! Try bringing the hay to the cow.':'We found everyone! Tap, drag, and explore together.',true);}
 function showExplore(end=false){generation++;board=null;renderDiscoveries($('barn-explore-discoveries'),true);$('barn-round-actions').hidden=!end;$('barn-replay-two').hidden=!save.completed.includes(2);show('barn-explore');if(!end)speak('Tap a friend, or drag something to a place it belongs.',true);}
 function renderDiscoveries(root,interactive,newId){root.innerHTML='';for(const id of save.discoveries){const b=document.createElement('button');b.className=`barn-object barn-${id}${id===newId?' new':''}`;b.dataset.barnObject=id;b.innerHTML=barnItem(id);b.setAttribute('aria-label',label(id));if(!interactive)b.disabled=true;else wireObject(b,root);root.append(b);}}
 function label(id){return({cow:'Cow. Tap to hear it moo. Drag hay here.',hen:'Hen. Tap to see it flap.',hay:'Hay. Drag it to the cow.',egg:'Egg. Drag it to the nest.',duck:'Duck. Tap it or drag it to the pond.',sheep:'Sheep. Tap to see it bounce.',pond:'Pond',flowers:'Flowers. Tap to see a butterfly.'})[id];}
 function reaction(node,cls,text,kind){node.classList.add(cls);setTimeout(()=>node.classList.remove(cls),1500);tone(kind);speak(text,true);}
 function wireObject(node,root){let drag=null;node.onclick=()=>{if(node.dataset.dragged==='1'){node.dataset.dragged='0';return;}const id=node.dataset.barnObject;if(id==='cow')reaction(node,'moo','Moo! The cow says hello.','moo');if(id==='hen')reaction(node,'flap','Flap, flap! The hen is busy.','tap');if(id==='duck')reaction(node,'swim','Splish, splash! The duck paddles.','splash');if(id==='sheep')reaction(node,'bounce','Baa! What a bouncy sheep.','baa');if(id==='flowers'){const f=document.createElement('i');f.className='barn-butterfly';node.append(f);setTimeout(()=>f.remove(),2100);tone('match');speak('A butterfly found the flowers!',true);}};node.onpointerdown=e=>{if(!['hay','egg','duck'].includes(node.dataset.barnObject))return;drag={x:e.clientX,y:e.clientY,moved:false};node.setPointerCapture(e.pointerId);node.classList.add('dragging');};node.onpointermove=e=>{if(!drag)return;const x=e.clientX-drag.x,y=e.clientY-drag.y;if(Math.hypot(x,y)>7)drag.moved=true;node.style.setProperty('--dx',x+'px');node.style.setProperty('--dy',y+'px');};node.onpointerup=e=>{if(!drag)return;const id=node.dataset.barnObject,target=id==='hay'?root.querySelector('[data-barn-object="cow"]'):id==='egg'?root.parentElement.querySelector('.barn-nest'):root.querySelector('[data-barn-object="pond"]'),r=target?.getBoundingClientRect();node.classList.remove('dragging');node.style.removeProperty('--dx');node.style.removeProperty('--dy');node.dataset.dragged=drag.moved?'1':'0';if(drag.moved&&r&&e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)drop(id,node,target,root);drag=null;};}
 function drop(id,node,target,root){if(id==='hay'){node.classList.add('nibbled');reaction(target,'happy','Crunch, crunch! The cow loves her hay.','moo');setTimeout(()=>node.classList.remove('nibbled'),1600);}if(id==='egg'){node.classList.add('nibbled');root.querySelector('[data-barn-object="hen"]')?.classList.add('sitting');target.classList.add('chick');tone();speak('Peep! A tiny chick says hello.',true);setTimeout(()=>{node.classList.remove('nibbled');target.classList.remove('chick');root.querySelector('[data-barn-object="hen"]')?.classList.remove('sitting');},3000);}if(id==='duck')reaction(node,'swim','Splish, splash! The duck paddles in the pond.','splash');}
 $('barnyard').onclick=()=>save.completed.includes(2)?showExplore():start(!save.completed.includes(1)?1:2);$('barn-cards').onclick=e=>{const c=e.target.closest('[data-barn-card]');if(c)childFlip(Number(c.dataset.barnCard));};$('barn-hint').onclick=hint;$('barn-pip').onclick=()=>speak($('barn-caption').textContent);$('barn-home').onclick=()=>{generation++;goHome();};$('barn-explore-home').onclick=goHome;$('barn-replay-one').onclick=()=>start(1);$('barn-replay-two').onclick=()=>start(2);$('barn-next').onclick=()=>roundId===1?start(2):showExplore();$('barn-voice').onclick=()=>{save.voice=!save.voice;if(!save.voice)try{speechSynthesis.cancel();}catch{}persist();setSoundButtons();};$('barn-effects').onclick=()=>{save.effects=!save.effects;persist();setSoundButtons();if(save.effects)tone();};setSoundButtons();
 return{start,showExplore};
}
