const levels=[
 {name:'Sunny Seeds',pairs:['🌻','🍓','🐝','🌈'],xp:50},
 {name:'Pond Pals',pairs:['🐸','🐞','🦋','🌷','🐌','🍄'],xp:60},
 {name:'Moonlight Meadow',pairs:['🌙','🦉','✨','🌿','🪻','🐇','🌼','🧚'],xp:90}
];
let levelIndex=0,firstCard=null,lockBoard=false,turns=0,matched=0,totalXp=0,soundOn=true;
const $=s=>document.querySelector(s);const grid=$('#card-grid');
function tone(freq=520,duration=.09){if(!soundOn)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.06,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch{}}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function drawDots(){ $('#level-dots').innerHTML=levels.map((_,i)=>`<i class="level-dot ${i===levelIndex?'active':''}"></i>`).join('') }
function startLevel(){const level=levels[levelIndex];firstCard=null;lockBoard=false;turns=0;matched=0;$('#level-label').textContent=`LEVEL ${levelIndex+1} · ${level.name.toUpperCase()}`;$('#level-title').textContent=levelIndex===0?'Find the matching friends':levelIndex===1?'Listen to your garden memory':'You are a garden star!';$('#turn-count').textContent=0;$('#xp-now').textContent=totalXp;$('#helper-text').textContent='Tap two cards to find a pair.';drawDots();grid.className=`card-grid pairs-${level.pairs.length}`;grid.innerHTML=shuffle([...level.pairs,...level.pairs]).map((emoji,i)=>`<button class="memory-card" data-value="${emoji}" aria-label="Hidden garden card ${i+1}"><span class="memory-card-inner"><span class="card-face card-back">?</span><span class="card-face card-front">${emoji}</span></span></button>`).join('');grid.querySelectorAll('.memory-card').forEach(c=>c.addEventListener('click',flipCard));show('#game-screen')}
function flipCard(e){const card=e.currentTarget;if(lockBoard||card===firstCard||card.classList.contains('matched'))return;card.classList.add('flipped');tone(500,.06);if(!firstCard){firstCard=card;return}turns++;$('#turn-count').textContent=turns;const second=card;if(firstCard.dataset.value===second.dataset.value){firstCard.classList.add('matched');second.classList.add('matched');matched+=2;tone(760,.14);firstCard=null;if(matched===levels[levelIndex].pairs.length*2)setTimeout(completeLevel,480)}else{lockBoard=true;tone(180,.12);setTimeout(()=>{firstCard.classList.remove('flipped');second.classList.remove('flipped');firstCard=null;lockBoard=false},720)}}
function rewardFor(level){const perfect=level.pairs.length; if(turns<=perfect)return level.xp;if(turns<=perfect+2)return Math.round(level.xp*.8);return Math.round(level.xp*.6)}
function completeLevel(){const gain=rewardFor(levels[levelIndex]);totalXp+=gain;const perfect=levels[levelIndex].pairs.length;const stars=turns<=perfect?3:turns<=perfect+2?2:1;$('#result-kicker').textContent=levelIndex===levels.length-1?'GARDEN COMPLETE!':`LEVEL ${levelIndex+1} COMPLETE`;$('#result-title').textContent=stars===3?'Super memory!':stars===2?'Lovely work!':'You did it!';$('#star-row').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#result-turns').textContent=turns;$('#result-xp').textContent=`+${gain}`;$('#result-message').textContent=levelIndex===levels.length-1?`You collected ${totalXp} / 200 garden stars. Pip is so proud of you!`:`You collected ${gain} stars this level. Keep growing!`;$('#next-button').innerHTML=levelIndex===levels.length-1?'Play again <span aria-hidden="true">↻</span>':'Next garden <span aria-hidden="true">→</span>';$('#confetti').innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i>';tone(880,.3);show('#result-screen')}
$('#start-button').addEventListener('click',()=>{levelIndex=0;totalXp=0;startLevel()});$('#next-button').addEventListener('click',()=>{if(levelIndex===levels.length-1){levelIndex=0;totalXp=0}else levelIndex++;startLevel()});$('#home-button').addEventListener('click',()=>show('#welcome-screen'));$('#sound-button').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♪':'×';e.currentTarget.setAttribute('aria-pressed',soundOn)});
